### PR TITLE
prep for release

### PR DESCRIPTION
**Pull request by peterbriggs42**

### CODE REVIEW

**Review by timabrmsn — APPROVED** [review]

**Comment by unparalleled-js** [comment]
It has not completed testing yet

**Review by unparalleled-js — CHANGES_REQUESTED** [review]
wait for testing complete

**Comment by unparalleled-js** [comment]
integ-1724

**Comment by timabrmsn** [comment]
> wait for testing complete

I just tested this myself and it passed.

**Review by unparalleled-js — APPROVED** [review]

**Review by timabrmsn — APPROVED** [review]

**Pull request merged**
