### PR TITLE
Fix arg doc

### PR DESCRIPTION
**Pull request by unparalleled-js**
### Description of Change ###

I forgot to update the arg name in the doc str so this does that

### Issues Resolved ###

- closes #

### PR Checklist ###
Did you remember to do the below?

- [n/a] Add unit tests to verify this change
- [n/a] Add an entry to CHANGELOG.md describing this change
- [x] Add docstrings for any new public parameters / methods / classes

### CODE REVIEW

**Review by kiran-chaudhary — APPROVED** [review]
Change LGTM, though I would not mention the unit 'bytes' in the arg name!  Reason being, unit is explained in the docstring and in future if the implementation detail changes to KB, MB etc we need not have to rename the argument name. so `archive_size_quota` or `quota_archive_size` whichever suits best seems more apt.

Approved, otherwise.

EDIT: Need to add/change a test case

**Comment by kiran-chaudhary** [comment]
Also a unit test should be changed if a function argument has changed, I see a change only in one src file!

**Review by kiran-chaudhary — CHANGES_REQUESTED** [review]
Missing unit test!?

**Comment by timabrmsn** [comment]
The existing unit test has the correct arg name, the only change here was the docstring which was incorrect.

**Review by timabrmsn — APPROVED** [review]

**Review by kiran-chaudhary — APPROVED** [review]

**Pull request merged**
